# Generated by Django 5.0.4 on 2024-05-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='default title', max_length=75)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('price', models.DecimalField(decimal_places=1, default='0', max_digits=19)),
                ('image', models.URLField()),
                ('release_date', models.DateField(default='01.01.2000')),
                ('lte_exists', models.BooleanField()),
            ],
        ),
    ]
